### ISSUE TITLE
Adding relative layout and changing its color

### ISSUE THREAD

**Issue by viktapas** [vikaskumar-vsk/ButtonCumGesture#1]
I guess the problem lies b/w line 16 to 30: https://github.com/vikaskumar-vsk/ButtonCumGesture/blob/master/app/src/main/java/com/vikaskumar/vsk/buttoncumgesture/MainActivity.java

**Comment by viktapas** [comment]
* Debug console:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.vikaskumar.vsk.buttoncumgesture, PID: 16936
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vikaskumar.vsk.buttoncumgesture/com.vikaskumar.vsk.buttoncumgesture.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6126)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                      at com.vikaskumar.vsk.buttoncumgesture.MainActivity.onCreate(MainActivity.java:37)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6126) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by imflash217** [comment]
change the following lines in ur mainActivity.java script:
 
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main); // <------- you forgot this.....

        ///Layout///
        // RelativeLayout buckysLayout = new RelativeLayout(this);  // <--- WRONG!!!, u r creating a completely new relative layout...it wont sync with ur XML file
        RelativeLayout buckysLayout = (RelativeLayout) findViewById(R.id.RelativeLayout);  // <------- you forgot this.....
        buckysLayout.setBackgroundColor(Color.YELLOW);

        ////Begin Button and Text Activity////
```

**Comment by imflash217** [comment]
this will help too: 
http://stackoverflow.com/questions/28193552/null-pointer-exception-on-setonclicklistener

**Comment by viktapas** [comment]
@vinaykumar2491 
so...what does this code line (`setContentView(R.layout.activity_main);`) actually do?

**Comment by imflash217** [comment]
it sets content for the java file......
w/o this u cannot access any component in your **layout xml** file from your java script......
this was the reason why your app was crashing and thats why the debugger was giving **null exception error**

**Comment by viktapas** [comment]
Okay you mean it sets content to view? 
right?

**Comment by imflash217** [comment]
Also, make sure to document the scripts properly.....currently its not well commented.....

if the answer solved the issue.....then u can close the #issue
